name: Child Action

on:
  push:
    branches:
      - main


jobs:
  build:
    uses: DibyajyotiMishra/GitActionsCommon/.github/workflows/common.yaml@main
  commit:
    name: Commit
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered common Workflow from child 🐭" 
